### PR TITLE
ci: Added semantic-release

### LINKED ISSUE #20: ci: add semantic-release
Add [semantic-release/semantic-release](https://github.com/semantic-release/semantic-release) to the project

### PR DESCRIPTION
**Pull request by trishanu-init**
## Fixes Issue

Closes #20 

## Changes proposed
-Added semantic-release
-Created file release.yml
-Created file .release.config.js
-Changed node version from 16 to 20

All new commits are grouped and can be released on a single click by running the release workflow.
This improves automation and makes it easier for the maintainer to release new version.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots
image

## Note to reviewers

Please make changes in the documentation for Semantic Commit Message format

### Summary by CodeRabbit

Release Notes:

- Chore: Updated GitHub Actions workflow trigger from `push` to `pull_request` on the `main` branch in `.github/workflows/lint.yml`.
- Chore: Upgraded Node.js version from 16 to 20 in `.github/workflows/lint.yml`.
- New Feature: Added a new GitHub Actions workflow for the release process in `.github/workflows/release.yml`.
- New Feature: Introduced configuration for semantic release in `src/release.config.js` and `.release.config.js`.
- Documentation: Enhanced the introductory message in `CONTRIBUTING.md`.

### CODE REVIEW

**Comment by trishanu-init** [comment]
@xkrishguptaa Please merge this PR against issue #20 and apply the hacktoberfest-accepted tag

**Review by xkrishguptaa — COMMENTED** [review]
Format all the files please

**Comment by trishanu-init** [comment]
@xkrishguptaa please ellaborate

**Comment by trishanu-init** [comment]
@xkrishguptaa please elaborate what you mean with formatting the files.

**Comment by xkrishguptaa** [comment]
the style is not consistent. please make sure it is styled exactly like our other files

**Review by xkrishguptaa — DISMISSED** [review]

**Comment by xkrishguptaa** [comment]
please resolve conflicts

**Comment by xkrishguptaa** [comment]
thank you

**Pull request merged**
